[project]
name = "houdini-megascans"
version = "0.1.0"
description = "A Quixel Bridge plugin for SideFX Houdini Solaris to import Megascans assets directly into the stage."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "houdini-component-builder@git+https://github.com/beatreichenbach/houdini-component-builder@v0.1.0",
]

[project.optional-dependencies]
dev = [
    "PySide6>=6.11",
    "python-semantic-release>=10.0",
    "qt-material-icons>=0.2,<1",
    "ruff>=0.16",
    "types-houdini>=21.0",
    "types-usd>=24.5",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["megascans*"]

[tool.semantic_release]
version_variables = ["megascans/__init__.py:__version__"]
version_toml  = ["pyproject.toml:project.version"]
build_command = """bash build.sh"""
assets = ["build/megascans-*.zip"]

[tool.semantic_release.remote]
ignore_token_for_push = true

[tool.ruff.format]
quote-style = "single"
