name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build ZIP file
        run: |
          cp src/*.json build/
          mkdir -p build/megascans
          cp src/menu build/megascans/
          mkdir -p build/python
          python3.11 -m pip install . --target build/python
          cd build
          zip -r ../megascans-${{ github.ref_name }}.zip .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: megascans-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}